version: '3.9'

services:
  go_app:
    container_name: go_app
    image: go-api-tutorial
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: 123456
      PORSTGRES_USER: postgres
      POSTGRES_DB: go_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
